In [7]:
%reload_ext autoreload
%autoreload 2

In [22]:
import numpy as np 

a = np.array([ [1, 2,3, 4], [9, 1, 2,54], [89, 68 , 39 , 90], [59, 820, 839, 10] ])

print (np.linalg.norm(a))

1185.36914081648


In [7]:
%reload_ext autoreload
%autoreload 2

import numpy as np 
from numericalmethods.matrices import *

r1 = [-209.0,87,-18,-3]
r2 = [6,1,98,7]
r3 = [-49,108,-2,-6]
r4 = [902, 89, 90, 455]

arr = np.array ([r1,r2,r3,r4])

print (arr)
arr = pivoting (arr)
print (arr)
arr = elimination (arr)
print (arr)
backsub(arr)
print (arr)


[[-209.   87.  -18.   -3.]
 [   6.    1.   98.    7.]
 [ -49.  108.   -2.   -6.]
 [ 902.   89.   90.  455.]]
[[ 902.   89.   90.  455.]
 [ -49.  108.   -2.   -6.]
 [   6.    1.   98.    7.]
 [-209.   87.  -18.   -3.]]
[[9.02000000e+02 8.90000000e+01 9.00000000e+01 4.55000000e+02]
 [0.00000000e+00 1.12834812e+02 2.88913525e+00 1.87172949e+01]
 [0.00000000e+00 0.00000000e+00 9.73908840e+01 3.90571544e+00]
 [0.00000000e+00 0.00000000e+00 1.38777878e-17 8.45703254e+01]]


NameError: name 'np' is not defined